{% set version = "0.13.2" %}

package:
  name: pyagrum
  version: {{ version }}

source:
  fn: pyagrum-{{ version }}.tar.bz2   # [unix]
  url: https://gitlab.com/agrumery/aGrUM/repository/archive.tar.bz2?ref={{ version }}  # [unix]
  sha256: d424dc35ebf2b3d3a36f4c76bc6bf8fdc635ebbbe5aa2953a091ef0baa8a8086  # [unix]

  fn: agrum-{{ version }}-py2.7-x86_64.zip   # [win64 and py27]
  url: https://github.com/openturns/build-agrum/releases/download/v{{ version }}/agrum-{{ version }}-py2.7-x86_64.zip  # [win64 and py27]
  sha256: 693b30501044c30d0cbbe80dbf228de3beb62aef7bcce4b237985bf67b70b8b1  # [win64 and py27]

  fn: agrum-{{ version }}-py3.6-x86_64.zip   # [win64 and py36]
  url: https://github.com/openturns/build-agrum/releases/download/v{{ version }}/agrum-{{ version }}-py3.6-x86_64.zip  # [win64 and py36]
  sha256: 0495a663e85d977e936fb2d29df0f037a001b8ec560401059e2a25fea7442e7d  # [win64 and py36]

  fn: agrum-{{ version }}-py6.7-x86_64.zip   # [win64 and py37]
  url: https://github.com/openturns/build-agrum/releases/download/v{{ version }}/agrum-{{ version }}-py3.7-x86_64.zip  # [win64 and py37]
  sha256: d424dc35ebf2b3d3a36f4c76bc6bf8fdc635ebbbe5aa2953a091ef0baa8a8086  # [win64 and py37]

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - numpy
    - pydotplus
    - matplotlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - pydotplus
    - matplotlib

test:
  requires:
    - ipython
  imports:
    - pyAgrum
    - pyAgrum.lib.bn2csv
    - pyAgrum.lib.bn2roc
    - pyAgrum.lib.bn2scores
    - pyAgrum.lib.bn_vs_bn
    - pyAgrum.lib.dynamicBN
    - pyAgrum.lib.notebook
    - pyAgrum.lib.pretty_print


about:
  home: http://agrum.gitlab.io/
  license: GPL3
  license_file: COPYRIGHT.txt
  summary: A wrapper for the Agrum library, to make flexible and scalable probabilistic graphical models.

extra:
  recipe-maintainers:
    - jschueller
    - ltorti
